# Generated by Django 4.2.2 on 2023-09-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('blood_type', models.CharField(max_length=2)),
                ('last_donation_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
