# Generated by Django 4.2.2 on 2023-09-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_blooddonor_last_donation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='blooddonor',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
